name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for frontend projects)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: soource_code/frontend

      - name: Run tests
        run: npm test
        working-directory: soource_code/frontend

      - name: Build project
        run: npm run build
        working-directory: soource_code/frontend
