name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Verify repo structure
        run: ls -R 
        
      - name: Set up Node.js (for frontend projects)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # run ./setup.sh to install dependencies
      - name: Install dependencies
        run: ./setup.sh
        working-directory: ./


      - name: Run frontend tests
        run: npm test
        working-directory: source_code/frontend
      
      - name: Run backend tests
        run: npm test
        working-directory: source_code/backend